export const PLANET_FILES = [
  'planet_map_01.glb',
  'planet_map_02.glb',
  'planet_map_03.glb',
  'planet_map_04.glb',
  'planet_map_05.glb',
  'planet_map_06.glb',
  'planet_map_07.glb',
  'planet_map_08.glb',
  'planet_map_09.glb',
  'planet_map_10.glb',
  'planet_map_11.glb',
  'planet_map_12.glb',
  'planet_map_13.glb',
  'planet_map_14.glb',
  'planet_map_15.glb',
  'planet_map_16.glb',
  'planet_map_17.glb',
  'planet_map_18.glb',
  'planet_map_19.glb',
  'planet_map_20.glb',
  'planet_map_21.glb'
];

export const config = {
  planetCountMin: 6,
  planetCountMax: 9,
  planetScale: 1000,
  orbitScale: 800,
  clusterRadius: 1.0,
  clusterWobble: 0.08,
  starfieldRadiusMin: 13000,
  starfieldRadiusMax: 34000,
  atmosphereRatioMin: 1.135,
  atmosphereRatioMax: 1.27,
  atmosphereTrimResponse: 0.05,
  atmosphereLevelResponse: 0.75,
  atmosphereBankResponse: 1.7,
  atmosphereApproachResponse: 1.45,
  atmosphereControlAltitude: 50,
  atmosphereSpaceTurnTransition: 50,
  shipPitchReorientDelay: 0.5,
  shipCaptureBlendTime: 1.0,
  shipTurnSpeedScale: 2.0,
  planetCaptureAltitude: 70,
  planetEscapeAltitude: 75,
  shipEscapeSpeed: 25,
  shipRecaptureDelay: 2.0,
  planetSurfaceSnapAltitude: 25,
  planetCaptureAtmosphereFactor: 0.95,
  surfaceOrbitPeriodMin: 38,
  surfaceOrbitPeriodMax: 42,
  atmosphereLiftFactor: 2.45,
  atmosphereDensityCurve: 1.25,
  atmosphereLiftMinSpeedFactor: 0.58,
  atmosphereLiftGoodSpeedFactor: 1.08,
  atmosphereLiftCruiseAuthority: 0.36,
  atmosphereLiftStallStart: 0.34,
  atmosphereLiftStallFull: 0.12,
  atmosphereStallPitchDownMin: 0.10,
  atmosphereStallPitchDownMax: 0.55,
  atmosphereDiveSpeedGain: 1.15,
  atmosphereClimbSpeedPenalty: 0.72,
  atmosphereDiveAccelResponse: 2.65,
  atmosphereClimbBleedResponse: 1.35,
  atmosphereCruiseBleedResponse: 0.82,
  atmosphereTerrainGuardStartRatio: 0.60,
  atmosphereTerrainGuardFullRatio: 0.20,
  atmosphereTerrainGuardMinAltitude: 10.0,
  atmosphereTerrainLookaheadTime: 5.5,
  atmosphereTerrainLookaheadFullTime: 1.35,
  atmosphereTerrainDiveStart: 0.05,
  atmosphereTerrainDiveFull: 0.70,
  atmosphereTerrainPullUpStrength: 3.5,
  atmosphereTerrainPullUpRateMin: 4.0,
  atmosphereTerrainPullUpRateMax: 16.0,
  atmosphereTerrainPullUpClimbDot: 0.52,
  atmosphereHardDiveOverrideStart: 0.94,
  atmosphereHardDiveOverrideFull: 1.0,
  atmosphereHardDiveOverrideAuthority: 0.76,
  atmosphereTerrainCrashAltitude: 1.5,
  crashRespawnDelay: 3.0,
  fighterTurnRate: 24.0,
  fighterVelocityAlign: 8.0,
  shipCamDistance: 6.8,
  shipCamHeight: 3.0,
  shipCamLag: 20.0,
  shipIdleThrust: 200,
  shipMaxThrust: 400,
  shipBoostThrust: 100,
  shipBoostDuration: 0.5,
  shipFuelRecharge: 0.3,
  shipFireCooldown: 0.22,
  shipProjectileSpeed: 100,
  shipProjectileLifetime: 8.0,
  shipProjectileSpread: 0.04,
  shipProjectileSize: 0.1,
  starScale: 300,
  planetMotionSpeedScale: 0.5,
  shipMinMaxSpeed: 20,
  shipAltMaxSpeedFac: 1.0,
  shipMuzzleOffset: 0,
  shipBrake: 40,
  shipDragSpace: 0.2,
  shipDragAtmosphere: 20.0,
  gravitySoftening: 0.22,
  fuelMoteCountPerPlanet: 10
};
