export const PLANET_FILES = [
  'planet_map_01.glb',
  'planet_map_02.glb',
  'planet_map_03.glb',
  'planet_map_04.glb',
  'planet_map_05.glb',
  'planet_map_06.glb',
  'planet_map_07.glb',
  'planet_map_08.glb',
  'planet_map_09.glb',
  'planet_map_10.glb',
  'planet_map_11.glb',
  'planet_map_12.glb',
  'planet_map_13.glb',
  'planet_map_14.glb',
  'planet_map_15.glb',
  'planet_map_16.glb',
  'planet_map_17.glb',
  'planet_map_18.glb',
  'planet_map_19.glb',
  'planet_map_20.glb',
  'planet_map_21.glb'
];

export const config = {
  debug: true,
  debugSeed: 0xC0FFEE,
  planetCountMin: 6,
  planetCountMax: 9,
  planetScale: 1000,
  orbitScale: 800,
  clusterRadius: 1.0,
  clusterWobble: 0.08,
  mothershipScaleFactor: 0.3,
  mothershipSpawnDelayMin: 28,
  mothershipSpawnDelayMax: 54,
  mothershipMaxCount: 2,
  mothershipHoldRadiusFactor: 2.0,
  mothershipFighterCountMin: 10,
  mothershipFighterCountMax: 15,
  mothershipFighterReleaseInterval: 2.6,
  fighterDiveAltitudeFactor: 1.25,
  fighterPatrolAltitudeFactor: 1.45,
  mothershipHoldAngularSpeedMin: 0.00036,
  mothershipHoldAngularSpeedMax: 0.00084,
  mothershipHoldBetaSpeedMin: 0.00012,
  mothershipHoldBetaSpeedMax: 0.00032,
  mothershipHoldReorientDuration: 4.5,
  mothershipSpawnDistanceMin: 2500,
  mothershipSpawnDistanceMax: 4200,
  mothershipApproachExponent: 1.4,
  mothershipApproachSpeedFactor: 0.02,
  mothershipApproachSpeedMinFactor: 12.0,
  mothershipApproachSnapFactor: 0.01,
  mothershipExitSpeedFactor: 0.02,
  enemyHitPoints: 10,
  mothershipHitPoints: 2000,
  shipProjectileDamage: 15,
  starfieldRadiusMin: 13000,
  starfieldRadiusMax: 34000,
  atmosphereRatioMin: 1.135,
  atmosphereRatioMax: 1.27,
  atmosphereTrimResponse: 0.05,
  atmosphereLevelResponse: 0.75,
  atmosphereBankResponse: 1.7,
  atmosphereApproachResponse: 1.45,
  shipPitchReorientDelay: 0.5,
  shipCaptureBlendTime: 1.0,
  shipTurnSpeedScale: 2.0,
  // Free-space gravity nose pull is temporarily disabled while we rework the model.
  freeGravityTurnRate: 0.0,
  freeGravityMaxTurnRate: 0.0,
  freeGravitySpeedDamping: 0.055,
  freeGravityNoRollSpeed: 3.5,
  freeGravityPlanetInfluenceScale: 1.0,
  freeGravitySunInfluenceScale: 0.35,
  freeGravityPlanetNearRangeScale: 1.08,
  freeGravityPlanetAtmosphereBufferScale: 0.08,
  freeGravityPlanetFarRangePadding: 1.0,
  freeGravitySunNearRangeScale: 1.35,
  freeGravitySunFarRangeScale: 7.5,
  freeSpaceControlScale: 0.5,
  freeSpaceYawRateMin: 0.72,
  freeSpaceYawRateMax: 1.65,
  freeSpacePitchRateMin: 0.72,
  freeSpacePitchRateMax: 1.65,
  freeFlightBankDecayResponse: 2.4,
  freeBrakeHalfLife: 2.0,
  freeBoostAcceleration: 50,
  freeCameraRollResponse: 2.4,
  deepSpaceSuspiciousDistance: 5000,
  atmosphereCaptureSpeedTransitionScale: 0.5,
  planetCaptureAltitude: 70,
  planetEscapeAltitude: 75,
  shipRecaptureDelay: 2.0,
  surfaceOrbitPeriodMin: 38,
  surfaceOrbitPeriodMax: 42,
  atmosphereDensityCurve: 1.25,
  atmosphereLiftMinSpeedFactor: 0.58,
  atmosphereLiftGoodSpeedFactor: 1.08,
  atmosphereLiftCruiseAuthority: 0.36,
  atmosphereLiftStallStart: 0.34,
  atmosphereLiftStallFull: 0.12,
  atmosphereStallPitchDownMin: 0.10,
  atmosphereStallPitchDownMax: 0.55,
  atmosphereCruiseAltitudeFactor: 0.5,
  fighterPatrolAltitudeErrorScale: 0.35,
  fighterPatrolPitchFloorMin: -0.75,
  fighterPatrolPitchFloorMax: 0.18,
  atmosphereDiveSpeedGain: 1.15,
  atmosphereClimbSpeedPenalty: 0.72,
  atmosphereDiveAccelResponse: 2.65,
  atmosphereClimbBleedResponse: 1.35,
  atmosphereCruiseBleedResponse: 0.82,
  atmosphereTerrainGuardStartRatio: 0.60,
  atmosphereTerrainGuardFullRatio: 0.20,
  atmosphereTerrainGuardMinAltitude: 10.0,
  atmosphereTerrainLookaheadTime: 5.5,
  atmosphereTerrainLookaheadFullTime: 1.35,
  atmosphereTerrainPullUpStrength: 3.5,
  atmosphereTerrainPullUpBoostScale: 0.45,
  atmosphereTerrainPullUpClimbDot: 0.52,
  atmosphereHardDiveOverrideStart: 0.94,
  atmosphereHardDiveOverrideFull: 1.0,
  atmosphereHardDiveOverrideAuthority: 0.76,
  atmosphereLevelResponseMin: 0.22,
  atmosphereBankDecayResponseMin: 0.6,
  atmosphereYawRateMin: 0.38,
  atmosphereYawRateMax: 0.98,
  atmosphereYawSpeedFactorMin: 0.55,
  atmosphereYawSpeedFactorMax: 1.0,
  atmospherePitchRateMin: 0.28,
  atmospherePitchRateMax: 0.52,
  atmosphereBankReturnRateMin: 1.4,
  atmosphereBankReturnRateMax: 3.3,
  atmosphereBankTurnScaleMin: 0.7,
  atmosphereBankTurnScaleMax: 1.0,
  atmosphereSpeedBlendDepthMin: 0.65,
  atmosphereSpeedBlendDepthMax: 1.25,
  atmosphereSpeedBlendBoostMin: 0.85,
  atmosphereSpeedBlendBoostMax: 1.1,
  atmosphereTrimResponseMin: 0.015,
  atmosphereTrimAltitudeScaleLiftMin: 0.12,
  atmosphereTrimAltitudeScaleLiftMax: 1.0,
  atmosphereTrimAltitudeScaleStallMin: 0.70,
  atmosphereTrimAltitudeScaleStallMax: 1.35,
  atmosphereTrimPitchClampMin: -0.14,
  atmosphereTrimPitchClampMax: 0.18,
  atmosphereTerrainCrashAltitude: 1.5,
  crashRespawnDelay: 3.0,
  shipCamDistance: 6.8,
  shipCamHeight: 3.0,
  shipCamLag: 24.0,
  shipCamTurnOffset: 1.0,
  shipCamPitchOffset: 1.0,
  shipCamBoostOffset: 1.0,
  shipCamOffsetResponse: 1.0,
  shipCamOffsetReturn: 2.0,
  shipBoostThrust: 20,
  shipBoostDuration: 0.5,
  shipFuelRecharge: 25.0,
  shipFireCooldown: 0.22,
  shipProjectileSpeed: 100,
  shipProjectileLifetime: 8.0,
  shipProjectileShipVelocityScale: 0.35,
  shipProjectileSize: 0.1,
  starScale: 300,
  planetMotionSpeedScale: 0.5,
  shipMinMaxSpeed: 20,
  shipAltMaxSpeedFac: 1.0,
  shipMuzzleOffset: 0,
  gravitySoftening: 0.22,
  fuelMoteCountPerPlanet: 10
};
