export const PLANET_FILES = [
  'planet_map_01.glb',
  'planet_map_02.glb',
  'planet_map_03.glb',
  'planet_map_04.glb',
  'planet_map_05.glb',
  'planet_map_06.glb',
  'planet_map_07.glb',
  'planet_map_08.glb',
  'planet_map_09.glb',
  'planet_map_10.glb',
  'planet_map_11.glb',
  'planet_map_12.glb',
  'planet_map_13.glb',
  'planet_map_14.glb',
  'planet_map_15.glb',
  'planet_map_16.glb',
  'planet_map_17.glb',
  'planet_map_18.glb',
  'planet_map_19.glb',
  'planet_map_20.glb',
  'planet_map_21.glb'
];

export const config = {
  planetCountMin: 6,
  planetCountMax: 9,
  planetScale: 10000,
  orbitScale: 8000,
  clusterRadius: 1.0,
  clusterWobble: 0.08,
  starfieldRadiusMin: 130000,
  starfieldRadiusMax: 340000,
  atmosphereRatioMin: 1.135,
  atmosphereRatioMax: 1.27,
  atmosphereTrimResponse: 0.05,
  atmosphereLevelResponse: 0.75,
  atmosphereBankResponse: 1.7,
  atmosphereApproachResponse: 1.45,
  atmosphereControlAltitude: 500,
  atmosphereSpaceTurnTransition: 500,
  shipPitchReorientDelay: 0.5,
  shipCaptureBlendTime: 1.0,
  shipTurnSpeedScale: 2.0,
  planetCaptureAltitude: 700,
  planetEscapeAltitude: 750,
  shipEscapeSpeed: 250,
  shipRecaptureDelay: 2.0,
  planetSurfaceSnapAltitude: 25,
  planetCaptureAtmosphereFactor: 0.95,
  surfaceOrbitPeriodMin: 38,
  surfaceOrbitPeriodMax: 42,
  atmosphereLiftFactor: 2.45,
  fighterTurnRate: 24.0,
  fighterVelocityAlign: 8.0,
  shipCamDistance: 6.8,
  shipCamHeight: 3.0,
  shipCamLag: 20.0,
  shipIdleThrust: 20,
  shipMaxThrust: 40,
  shipBoostThrust: 1000,
  shipBoostDuration: 4.0,
  shipFuelRecharge: 10.0,
  shipFireCooldown: 0.22,
  shipProjectileSpeed: 280,
  shipProjectileLifetime: 8.0,
  shipProjectileSpread: 0.04,
  shipProjectileSize: 0.2,
  starScale: 1000,
  planetMotionSpeedScale: 0.5,
  shipMinMaxSpeed: 200,
  shipAltMaxSpeedFac: 1.0,
  shipMuzzleOffset: 0,
  shipBrake: 400,
  shipDragSpace: 0.2,
  shipDragAtmosphere: 20.0,
  gravitySoftening: 2.2,
  fuelMoteCountPerPlanet: 10
};
